name: AWS example workflow
on:
  push
env:
  BUCKET_NAME : "OIDC-SHZB0011"
  AWS_REGION : "us-east-1"
permissions:
  id-token: write  
  contents: read    
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v5
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@<commit/SHA>
        with:
          role-to-assume: arn:aws:iam::751811337288:role/OIDC-Role
          role-session-name: samplerosession
          aws-region: ${{ env.AWS_REGION }}

